# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Yarn CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn install` command
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          email: gwprice@mac.com
          build_dir: dist
          branch: website

